version: 2
orbs:
   azure-acr: circleci/azure-acr@0.1.4
   
jobs:
  build:
    docker:
      
      - image: circleci/node:10.15.0

      
    working_directory: ~/repo

    steps:
      - checkout

      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      #- run: yarn install
      - run: npm install
      
      - run: npm install mocha

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run: npm run test
      
      - run: |
          set -xu
          mkdir -p /tmp/artifacts
          ls -lrt
          cp -r ./* /tmp/artifacts/
      
      - store_artifacts:
          path: /tmp/artifacts
  
 
       - azure/build-and-push-image:
           login-server-name: bridgelabz.azurecr.io # e.g. {yourregistryname}.azure.io
           registry-name: bridgelabz
           repo: bridgelabz.azurecr.io/socketchatapp:latest
           filters:
             branches:
               only: master
               
  #deploy-stage:
  #  docker:
  #    - image: circleci/node:10.15.0
  #  working_directory: ~/repo
      
  #  steps:
  #    - run: npm start

      # Upload test results
      #- store_test_results:
      #    path: /tmp/test-reports
