version: 2
jobs:
  build:
    docker:
      
      - image: circleci/node:10.15.0

      
    working_directory: ~/repo

    steps:
      - checkout

      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      #- run: yarn install
      - run: npm install
      
      - run: npm install mocha

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run: npm run test
      
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports
